name: Sync YAML from Main to Test

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Python script to transform YAML files
        run: python .github/scripts/update_files.py

      - name: Create Pull Request to Test
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
        with:
          title: "Sync YAML changes from Main to Test - ${{ github.ref_name }}"
          body: "Automated PR to sync YAML files from Main to Test."
          commit-message: "Updated Test's config!"
          branch: "test"
          base: main
